# Make a copy of this file called config.yaml with your chosen edits

#Discord API settings. Don't add or remove any of these.
discord:
  #Provide your login token
  token: "TOKEN"      
  #Manage requested intents                  
  intents:        
    message_content: True #Turn this off if you don't use prefix commands and the bot doesn't need to see message content   
    members: False #Change to true if the bot needs to know about users
    guilds: True #Leave this as true unless you know you don't need it
    reactions : False #Change this to true if your bot needs to interact with message reactions

#About info
#Describe your bot!
about:
  title: "boilerBOT"
  desc: "a bot boilerplate. Find us on github!"
  url: "https://github.com/quartzshard"

#Bot settings
#Add options for your bot under here. Options can be removed if unneeded, but is unrecommended.    
options:
  #Bot Command Prefix 
  prefix: "!" 
  #Should core commands be registered as slash commands?
  slashcommands: True
  #Store data in a json over restarts?
  persist: False
  #Message embed settings
  embed:
    #Delete last message when new one sent?
    cleanup: True
    colour:
      #RGB values for colour presets
      default:
        r: 0xb4
        g: 0xeb
        b: 0xeb
      error:
        r: 0xff
        g: 0x00
        b: 0x00
    #Thumbnail image URL
    thumbnail: ""
  #Logging behaviour
  logging:                              
    #WARNING! if you disable all logging and something breaks, fixing it will be very difficult. 
    #Recommend you leave console logging enabled as a minimum
    #Enable logging to console
    logToConsole: False       
    #Enable logging to a file
    logToFile: False
    logFilePath: ""